# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b2aeb89aaf2404cd65f960ba6911a3e2029a1635349b8ec5fe4f668075475467686a705e761add735d39d07912668b45e81c07a3b4e22f80531b311f10d2ec6

test:
  secret_key_base: d5db2d414a0e7961f1c7734eb65f5e6fca159e95a3e388f8ad95603705dfb44a76d86aa92bcc8be05bcc01d3ded0551b9569b0172a1d06fc3e98b8fb5179e941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
